# Generated by Django 3.2.5 on 2021-09-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='create_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='update_date',
            new_name='last_upd',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='create_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='update_date',
            new_name='last_upd',
        ),
    ]
